"""Initial migration

Revision ID: c0ce7fd28b20
Revises: 
Create Date: 2023-07-07 19:08:47.814100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c0ce7fd28b20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.drop_table('USER')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USER',
    sa.Column('NAME', mysql.VARCHAR(length=11), nullable=False),
    sa.Column('NUMBER', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('REG_DATE', sa.DATE(), nullable=False),
    sa.Column('LAST_LOGIN', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
